version: '2'
services:
    backend:
        ports:
          - '9123:9123'
        build:
            context: .
            dockerfile: Dockerfile-go
        restart: on-failure
        container_name: backend
        depends_on:
          - db



    db:
        restart: on-failure
        ports:
          - '8002:3306'
        volumes:
          - ~/db:/var/lib/mysql
        image:
          mysql:8.0.13
        container_name: mysqldb
        environment:
            - MYSQL_ROOT_PASSWORD=1234
            - MYSQL_USER=1234
            - MYSQL_PASSWORD=1234
